name: pre-push
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instala as dependencias
        run: npm i
      - name: Roda o linter
        run: npm run lint